### ISSUE TITLE
Is there any way to make this work for other boorus?

### ISSUE THREAD

**Issue by timo103** [pseudonymous/better-better-booru#100]
Or is it purely for Danbooru? There's a lot of boorus that don't do image resizing and I was hoping this could fix that.

**Comment by Moebius-Strip** [comment]
Unless you're dealing with a booru that keeps up to date with Danbooru's updates, probably not. With so many miscellaneous tweaks and such, trying to make the current script work across multiple boorus would be difficult if not impossible.
