### ISSUE TITLE
Script isn't working

### ISSUE THREAD

**Issue by Moebius-Strip** [pseudonymous/better-better-booru#103]
Danbooru changed its JavaScript and I don't think I still have access to all of its functions and methods anymore. Might be the death of this script. ;P

**Comment by bluefiberbread** [comment]
https://github.com/r888888888/danbooru/issues/3795
Could give it a try ^^

**Comment by tallos** [comment]
I really hope you can find a workaround or fix, danbooru is pretty damn terrible without the script.

**Comment by A-Loli** [comment]
oh boy, atleast a part of these features will be better than nothing

**Comment by Moebius-Strip** [comment]
I haven't messed with some parts of this for so long that I forget how much it may or may not rely on Danbooru's JavaScript. I'll be taking a real look either tonight or over the weekend when I have time. For now, it's off to work I go~.

**Comment by Theo1996** [comment]
>Danbooru.note not defined , on mozilla console
on latest version RIP

**Comment by r888888888** [comment]
I can add hooks. Just post in that ticket with the functions you need access to.

**Comment by A-Loli** [comment]
Thank you @r888888888  !, you've been helping the community alot since this update.

**Comment by Moebius-Strip** [comment]
Got back from work after 11:00 last night and I'll be in and out of work Saturday and Sunday, but I searched the file and created a (hopefully complete) list of all the Danbooru object references in it. It'll be in the issue.

**Comment by tallos** [comment]
much of the functionality seems to be restored now.

**Comment by Eankun** [comment]
Aaand it is broken again. Still works on some pages (popular, for example) but broken on images.
Or is it just me?

**Comment by Moebius-Strip** [comment]
The "post tag titles" option ended up breaking, but it's fixed as of 8.2.2.
