### ISSUE TITLE
"Risize Mode" don't use all the Height available on screen.

### ISSUE THREAD

**Issue by FinderX** [pseudonymous/better-better-booru#108]
I notice the image not resize properly to use the available space on Height, in width is fine tho.
Here I attach an example.
![screenshot from 2018-10-11 02-09-56](https://user-images.githubusercontent.com/8683793/46782539-fb047b80-ccfc-11e8-95e8-2c273caf3007.png)

**Comment by Moebius-Strip** [comment]
Even with width, some space that is available isn't used. As for the height, I've decreased the amount of pixels left free from 40 to 10 in version 8.2.3. Leaving the resized content smaller than the actual height makes it easier for the content to be positioned entirely within view.
