### ISSUE TITLE
Suggestion: add a few features from "Danbooru miscellaneous tweaks"

### ISSUE THREAD

**Issue by worldendDominator** [pseudonymous/better-better-booru#47]
1) +/- at tag names add tags to the search box instead of starting a new search.
2) Option to display score and/or favcount under thumbnails.
3) Option to display comment score near vote up/down/unvote links.

**Comment by Moebius-Strip** [comment]
Just popping in to say I've seen this and it should be simple enough. For 1, I'd need to make a few changes to the existing tag list options, but they're changes I was already considering. It would be a good time for it. For 2 and 3, I'd probably end up spending more time on styling things than actually making it work. I'm considering some options for these changes and will most likely lump them in with the renovations I'm already neck deep in so it probably won't be very soon...

Some initial options I've already thought of:
* Concerning the behavior of the score/favs under the thumbnails option in the comments section, wouldn't it be better to just have the favorites get added to the right of the existing score display? Or is displaying the score (a second time) and favs below the thumbnail better? Unnecessary repetition/clutter or consistency?
* For the comment scores, displaying the score is simple enough, but how about a secondary option that allows it to act as protection against accidental vote clicks? As an example, the displayed score would actually be a link that takes the place of the vote up and down links. Clicking it would reveal the voting links to the right of it.

**Comment by Moebius-Strip** [comment]
Popping in again to say I've basically added all of these suggestions and they'll be in the next version. My implementations will all be styled a bit differently, of course.

One thing about the first suggestion for +/- links might be of special interest for you. I've made the script more cooperative with other scripts so if you don't like my implementation of those links, you can use the tweak script's +/- links in combination with this script's next version.

**Comment by Moebius-Strip** [comment]
Next version on the way out.
