### ISSUE TITLE
Hidden Tags broken

### ISSUE THREAD

**Issue by Knobibrot** [pseudonymous/better-better-booru#55]
Some time ago, hidden tags stopped displaying for me. Sometimes the thumbnail will display but when I go to the full view I always get a "Better Better Booru: Due to a lack of provided information, this post cannot be viewed.". However, the readme still claims that bbb will display hidden tags. So, is it just me or is it broken for everyone?
I am using Chrome on Windows 8.1.

**Comment by Moebius-Strip** [comment]
Using the latest version of Chrome and this script, I'm not encountering any problems with hidden posts. Going by that message though, you're not using the [most recent version](https://github.com/pseudonymous/better-better-booru/raw/master/better-better-booru.user.js) of the script. What version are you using?

**Comment by Knobibrot** [comment]
6.2.2
I thought it was the newest version, because when I click on look for updates, it doesn't find any.

**Comment by Knobibrot** [comment]
I just copy pasted the newest script and it works now.

**Comment by Moebius-Strip** [comment]
Yep, you got stuck at that version when http://userscripts.org/ went down for good. Without that site, there wasn't any way for automatic updates to work. Starting with the next version (6.3), [Greasy Fork (only accessible with an account)](https://greasyfork.org/en/scripts/3575-better-better-booru) / [Sleazy Fork (accessible with no account)](https://sleazyfork.org/en/scripts/3575-better-better-booru) started being the userscripts.org replacement. There should be another update to fix some issues related to video content posts.
