### ISSUE TITLE
Direct Download tags are rendered for blacklisted images

### ISSUE THREAD

**Issue by throwaway002** [pseudonymous/better-better-booru#61]
This means that DownThemAll (for example) will also download blacklisted images, which likely is not what people want.

Tested with:
Firefox 44.0.2

**Comment by Moebius-Strip** [comment]
I suppose that thumbnails filtered out with the quick search should probably be omitted from the direct downloads as well. It should be fine If the blacklist and quick search change the direct download URLs of affected posts to "#" to disable the download and change it back to the file URL to re-enable it. As long as there aren't any unwanted side effects, it'll be faster than completely deleting/recreating the links each time some filter is toggled. I'll be rolling the idea around in my head at work today and start tinkering tonight.

**Comment by Moebius-Strip** [comment]
Published my initial plan for disabling DDLs on filtered posts. If you'd like, you can test it out from the following link while I do my paranoid bug testing dance ritual before the official version release:
https://github.com/pseudonymous/better-better-booru/raw/no-filtered-ddl/better-better-booru.user.js

**Comment by throwaway002** [comment]
Works a treat, thanks.
