### ISSUE TITLE
possible to hide pictures already seen?

### ISSUE THREAD

**Issue by ghost** [pseudonymous/better-better-booru#65]
would love this feature :)

doesn't have to be hidden but any possible way to indicate it's already been viewed would be great

**Comment by Moebius-Strip** [comment]
I'm currently in the middle of changing the scripts storage methods so it might take a bit. When you talk about indicating pictures that have already been viewed, you're talking about somehow marking the thumbnails, right? Any thoughts about how long BBB should remember that a post has been viewed? Until the page is left? Until the tab is closed? Until the window is closed? Or possibly for X amount of posts?

**Comment by kunikomithra** [comment]
i'd like it to remain permanently but an option to completely erase every image you've seen at any time would be cool too.

also, it'd be neat if you could add a feature that would allow us to temporarily hide thumbnails that's not pending/flagged/deleted/child/parent whatever. 
http://i.imgur.com/EE0VcY5.jpg <- like this, let's say i only want to see child/parent which would "hide" every other thumbnail. what do you think?

**Comment by Moebius-Strip** [comment]
I'm still considering the options for how this would work out in the end and whether it can be put into the current script while playing nicely with everything else.

> i'd like it to remain permanently but an option to completely erase every image you've seen at any time would be cool too.

I'm not sure I can make "unlimited" an option for storing image IDs. Performance and storage space are both concerns. Alternatively, 10,000 maximum posts in the history (like the thumbnail info cache limit) should be more than enough, right?

> also, it'd be neat if you could add a feature that would allow us to temporarily hide thumbnails that's not pending/flagged/deleted/child/parent whatever.
> http://i.imgur.com/EE0VcY5.jpg <- like this, let's say i only want to see child/parent so it would "hide" every other thumbnail. what do you think?

You can use the quick search option to find specific posts in a list of results. If I search Danbooru for "scathach_(fate/grand_order) limit:200" and use "~parent:any ~child:any -rating:e" in the quick search, it will display [safe and questionable posts with children or a parent](http://i.imgur.com/2TTMHvE.jpg). The other things you mentioned can be detected with "status:active", "status:pending", "status:deleted", "status:flagged", and "status:banned".

**Comment by kunikomithra** [comment]
oh so that's where the quick search is, on the top right corner. thanks lol 

i believe 10k is a reasonable number

**Comment by Moebius-Strip** [comment]
Having more time to look at it, I've realized one problem is syncing things between tabs/windows. I'm going to have to ponder a way of sharing information and detecting changes to it that doesn't result in overkill.

**Comment by Moebius-Strip** [comment]
I've looked at somewhat new JavaScript options, but they all have security that's too tight for communicating information in this type of situation. Seems the only way to share information is to set up a system using the "focus" and/or "mousemove" events that would periodically check the script's history cache for a change upon user activity in the page and update the page accordingly. The marking of viewed posts couldn't really be instantaneous in all cases.
