### ISSUE TITLE
At this time 29/07/2016. It isn't working.

### ISSUE THREAD

**Issue by SetArk** [pseudonymous/better-better-booru#67]
Maybe the new update on Tempermonkey broke it.
Maybe danbooru changed something on their site? 
But for some reason, i cannot make it work.

**Comment by Moebius-Strip** [comment]
I haven't managed to run into any problems in the latest versions of  Chrome or Opera while using Tampermonkey. The only problem I've had is actually getting Opera to work at all. I don't know why it suddenly started being an issue... Unless your settings have gotten corrupted or you're using another script/extension that's causing a problem, I'm not sure what the problem could be. You can use "Control + Shift + J" to open the console in your browser and try to use BBB on Danbooru. If there's an error, it should show up in the console.

**Comment by Moebius-Strip** [comment]
Guess I'll close this now...?
