### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by elrichzann** [pseudonymous/better-better-booru#68]
Script:
C:\Users\XXXXXX\AppData\Local\Temp\Rar$Dla0.345\better-better-booru.user.js
Line:      9502
Char:     2
Error:    "document" is undefined
Code:    800A1391
Source:  Microsoft JScript runtime error

I keep getting this error.. How do i run the script with Tampermonkey?

**Comment by elrichzann** [comment]
Also, When i just type in the code it says unexpected end of code and https problem, fixed the https but still says unrecoverable error 100% scanned

**Comment by Moebius-Strip** [comment]
Using clean installs of the most recent releases of Firefox, Opera, and Chrome with Tampermonkey doesn't cause me any problems, but maybe I misread your post.

Are you asking how to install and use Tampermonkey or how to make the script work with Tampermonkey? The fact that "document" is undefined makes this sound like a security/permission error where the script isn't being allowed to use JavaScript on the page. Unless something is making the script run before the page even begins to be ready, the document object should pretty much always exist when this script runs.
