### ISSUE TITLE
Not Working Right Now

### ISSUE THREAD

**Issue by DuckFuzzy** [pseudonymous/better-better-booru#69]
Hey!
So i just wanted to say, i love this Script, but! For some reason, right now, it is not working!
I'm using Better Better Booru - 7.2.5, on Tapermonkey 4.1.1.10, on Chrome Version 53.0.2785.116 m

I can, also, post SSs showing, that even with the BBB online, and enabled, the Option to open and configure the BBB (IF i remember corectly, it would be "BBB Options", near Wiki and Pools ) does not appear.
So, what, do you thing could it be? Is it really broken, or is it just me? Should i try with Firefox and Greasemonkey?

Edit: So, i can confirm, that the problem, is on Chrome. Just downlaoded Greasemonkey and Firefox, and it is indeed working over there, the problem, seens to be on Chrome and Tampermonkey.

**Comment by Moebius-Strip** [comment]
Using completely clean installs, BBB works for me on the latest versions of everything so unless Chrome fixed something, there might be another extension/script causing a problem or there's a particular combination of settings that are conflicting. If you're still having an issue, you can try disabling various extensions and/or provide a copy or your settings and I will try them for myself.

Chrome Version 53.0.2785.143 m (64-bit)
Tampermonkey Version 4.1.10
BBB Version 7.2.5
