### ISSUE TITLE
Usage of localStorage

### ISSUE THREAD

**Issue by JingJang** [pseudonymous/better-better-booru#71]
Hi,
Please use GM_setValue and GM_getValue for storing non-temporary data. For privacy, many users have the localStorage wiped after a restart.
Thanks

**Comment by Moebius-Strip** [comment]
I've actually already lined this change up for the next update, but you can go ahead and test it out by installing the [current work in progress](https://github.com/pseudonymous/better-better-booru/raw/gm-functions/better-better-booru.user.js) from the other branch. A complete [list of changes](https://github.com/pseudonymous/better-better-booru/compare/gm-functions?expand=1) is also available. Just make sure you backup your settings first.

**Comment by JingJang** [comment]
A late thank you.

**Comment by Moebius-Strip** [comment]
Suitable for a late update. <_<;
