### ISSUE TITLE
Unexpected error while trying to initialize autocomplete for the quick search

### ISSUE THREAD

**Issue by FinderX** [pseudonymous/better-better-booru#73]
This error appears recently.

**Unexpected error while trying to initialize autocomplete for the quick search. (Error: cannot call methods on autocomplete prior to initialization; attempted to call method 'widget')**

**Comment by Moebius-Strip** [comment]
This is fixed in the latest version (7.3) that should be up on Fork in the near future. You can get it from [GitHub](https://github.com/pseudonymous/better-better-booru/raw/master/better-better-booru.user.js) right now if you'd like.

**Comment by FinderX** [comment]
Thanks! is working perfect now.
