### ISSUE TITLE
Clean Links Don't Work

### ISSUE THREAD

**Issue by GirlsCantKissGirls** [pseudonymous/better-better-booru#75]
As the topic says.  With clean links enabled you still get all the tags in the url. The update from today broke it.

**Comment by Moebius-Strip** [comment]
I can't reproduce this problem.

Can you provide me with:
* What browser you're using.
* Your browser version.
* A backup of your BBB settings for testing on my end.

**Comment by GirlsCantKissGirls** [comment]
Firefox
53.0 Most up to date version

[BBB Settings.txt](https://github.com/pseudonymous/better-better-booru/files/956821/BBB.Settings.txt)

**Comment by Moebius-Strip** [comment]
With Firefox 53 and your settings, I still can't find any thumbnail links that have the extra tag information after the post ID number. Is there another script running on Danbooru that might be the problem?

**Comment by GirlsCantKissGirls** [comment]
I don't have any other scripts conflicting with danbooru. I did a clean install of BBB and the issue still persists. It was working perfectly fine earlier today before the update. My friend also has the same issue, the new update broke clean links.

**Comment by Moebius-Strip** [comment]
That's not what the "clean links" option does. It only removes the query portion of post URLs in thumbnail links on Danbooru (example: https://danbooru.donmai.us/posts/1?tags=1girl+id:1 would become https://danbooru.donmai.us/posts/1) and has nothing to do with the direct image URLs. If you want the tag information stripped from image URLs.

You want the "disable tagged filenames" option under the preferences tab that is new as of version 7.3. That option was added after Danbooru changed the filename format default. It should change all the image URLs to their simple MD5 format.

**Comment by GirlsCantKissGirls** [comment]
Thanks that works. Closing the issue now.
