### ISSUE TITLE
On Android ?

### ISSUE THREAD

**Issue by RandomAndroidUser** [pseudonymous/better-better-booru#81]
How can I use it on Android?
I have already Firefox and an userscript manager on it.

Thanks.

**Comment by Moebius-Strip** [comment]
To be honest, you probably don't. I don't have a smartphone so I have no testing as far as phones go. I'm not sure if working in compatibility would be feasible or if a completely separate script for phones would be the only option.

**Comment by DanteDraconi** [comment]
I use Dolphin with the addons Tampermonkey and Jetpack. Works fine but sometimes it's finicky and won't load properly.
