### ISSUE TITLE
Loli/shota images disappear from search even though they shoudn't

### ISSUE THREAD

**Issue by worldendDominator** [pseudonymous/better-better-booru#84]
My user level normally lets me see loli/shota images. However, with BBB, loli and shota images disappear from search results about a second after their thumbnails are loaded.

But not always. Sometimes the search is displayed without problems, for example, if I just search for "loli", or for an artist. But if the query includes any copyright or character tags, the thumbs are gone. Some general tags break the search, some don't; same about metatags.

This  only happens when BBB is on.

**Comment by worldendDominator** [comment]
The same thing happens with banned images.

**Comment by Moebius-Strip** [comment]
Oh dear, not the higher than basic account thing again. <_<

The 7.4.1 update is just a quick fix to stop error message hell and questions about what happened. Access to the options has been removed, but everything else is still the same. I'll have to actually weed out all the useless stuff and redo other parts to make things functional. In your case, [rolling back to 7.4](https://greasyfork.org/en/scripts/3575-better-better-booru?version=205253) would fix everything for the time being or you could edit the following lines (lines 437-440 or 435-438) and change "false" to "true" as needed:
```
	var show_loli = false;
	var show_shota = false;
	var show_toddlercon = false;
	var show_banned = false;
```

**Comment by Moebius-Strip** [comment]
Still work to do, but you test the current work in progress here:
https://github.com/pseudonymous/better-better-booru/raw/hidden-update-test-branch/better-better-booru.user.js

Changes so far can be viewed here:
https://github.com/pseudonymous/better-better-booru/compare/hidden-update-test-branch?expand=1

**Comment by sirioth** [comment]
And where do i write true or false on it.

This what those lines shows : // Script variables.
	// Global
	var show_loli = bbb.user.show_loli;
	var show_shota = bbb.user.show_shota;
	var show_toddlercon = bbb.user.show_toddlercon;
	var show_banned = bbb.user.show_banned;
	var deleted_shown = (gLoc === "search" && /^(?:any|deleted)$/i.test(getTagVar("status"))); // Check whether deleted posts are shown by default.
	var show_deleted = deleted_shown || bbb.user.show_deleted;
	var direct_downloads = bbb.user.direct_downloads;
	var post_link_new_window = bbb.user.post_link_new_window;

**Comment by sirioth** [comment]
Well this is what i am getting https://imgur.com/du8VCV9

**Comment by sirioth** [comment]
Any idea how to fix it

**Comment by Moebius-Strip** [comment]
If you have a basic account, you can't backtrack to version 7.4. The options will be broken. Only gold and above accounts could revert to 7.4 with no problems. There are currently no plans to reinstate the hidden post options by using outside information.
