### ISSUE TITLE
When will gold accounts only tags and deleted artworks come back?

### ISSUE THREAD

**Issue by modical** [pseudonymous/better-better-booru#86]
Is it even possible?

**Comment by bluefiberbread** [comment]
I'd like to know as well, before I purchase Gold.

**Comment by GirlsCantKissGirls** [comment]
I'm pretty sure Moebius-Strip is going to stay away from this entire thing, it's been known for a long time and he's just been silent about it.

**Comment by pseudonymous** [comment]
Sorry for not clarifying my position on this much sooner, but the answer is no. There are workarounds proposed in another thread and users willing to maintain it, but doing so does not sit right with me.

@Moebius-Strip asked me about it on IRC when this first came up in August, and my response then also was that I'd be much more comfortable admitting that the jig is up - API has been fixed, upgrade your account or use something without the user restrictions (e.g. Gelbooru).

Danbooru *definitely* knew about the API exposing that info for years before finally patching patching it. I will respect their decision to stop providing the info on these posts. I don't think this will be a popular decision, but it feels like the right thing to do.
