### ISSUE TITLE
Suggestion: Add "Popular" in Posts, Danbooru remove this

### ISSUE THREAD

**Issue by FinderX** [pseudonymous/better-better-booru#90]
Please return that option in his rightful place.

**Comment by Moebius-Strip** [comment]
Added in as part of the next version under the layout tab's misc section. Current work in progress can be tested [here](https://github.com/pseudonymous/better-better-booru/raw/layout-the-options/better-better-booru.user.js). Current changes can be seen [here](https://github.com/pseudonymous/better-better-booru/compare/layout-the-options?expand=1).
