### ISSUE TITLE
Enabling "Random Post" link/shortcut on individual posts

### ISSUE THREAD

**Issue by EucariS-RespeR-ErrU** [pseudonymous/better-better-booru#91]
Danbooru has removed "Random Post" link/keyboard shortcut (R) when viewing individual posts/pages, it only works when viewing search result or the main posts page. There are small userscripts available that fix this issue, but it would be nice to have it in BBB.

**Comment by EucariS-RespeR-ErrU** [comment]
The removal is mentioned here: https://github.com/r888888888/danbooru/issues/3318

**Comment by EucariS-RespeR-ErrU** [comment]
Agh, github loves to link issues together.. Anyway, removal is mentioned on danbooru's github at "Resolution with Random on Post/Show #3318" thread.

**Comment by Moebius-Strip** [comment]
I've added it in for the next version under the layout tab's misc section. Current work in progress can be tested [here](https://github.com/pseudonymous/better-better-booru/raw/layout-the-options/better-better-booru.user.js). Current changes can be seen [here](https://github.com/pseudonymous/better-better-booru/compare/layout-the-options?expand=1).
