### ISSUE TITLE
Old posts don't display images

### ISSUE THREAD

**Issue by worldendDominator** [pseudonymous/better-better-booru#93]
Very old posts link images from the server raikou1.donmai.us. When BBB is active, character/copyright/artist are added to the image link, which makes it stop loading.

Example: https://danbooru.donmai.us/posts/182341 (NSFW)
Link without BBB: https://raikou1.donmai.us/60/c4/60c4de6b4839908c40c39dce56ab6388.png
Link with BBB: https://raikou1.donmai.us/60/c4/__original_drawn_by_ze_sawakihein__60c4de6b4839908c40c39dce56ab6388.png (error 404)

I solved this eventually by turning on the Disable Tagged Filenames setting, but it still looks like something that needs to be fixed.

**Comment by Moebius-Strip** [comment]
r888888888/danbooru#3542 references this as well and I was hoping it would be fixed on Danbooru, but I may have to go ahead and merge b3805f9613abe8366e5978a44eb23249965d422d that I committed 2 weeks ago and then revert it when and if Danbooru does fixes that server issue.

**Comment by bluefiberbread** [comment]
I'm unable to load images, not just old, but both new and old.

**Comment by Moebius-Strip** [comment]
Danbooru seems to have worked out its server problems now.
