### ISSUE TITLE
Error retrieving post information (JSON Code: 500 Internal Server Error).

### ISSUE THREAD

**Issue by bluefiberbread** [pseudonymous/better-better-booru#94]
Not sure what's causing it, but what does it mean?

**Comment by worldendDominator** [comment]
It says Internal Server Error. The problem is probably on Danbooru's side.
Danbooru servers have been rather unstable recently (several times for several hours over the last few weeks).

Just in case, where in particular did you get this error?

**Comment by bluefiberbread** [comment]
http://danbooru.donmai.us/posts?limit=200&ms=1&page=6&tags=izayoi_sakuya&utf8=%E2%9C%93

**Comment by Moebius-Strip** [comment]
Definitely server problems on Danbooru's end, but they seem to be doing better now.
