### ISSUE TITLE
Is the loli/shota hidden images ever going to be shown using this plugin?

### ISSUE THREAD

**Issue by Pink-Devil** [pseudonymous/better-better-booru#95]
Been a while since the update to fix this issue, will it ever become functional again?

**Comment by Moebius-Strip** [comment]
Unless there is a change of heart, this script won't be supporting the viewing of censored posts. You can have a look at issues #86 and #82 for more info.

**Comment by Pink-Devil** [comment]
Thanks, I managed to get the loli/shota images uncensored. But the very recent images are still censored for some reason.
