### ISSUE TITLE
The script currently doesn't work in certain areas while Danbooru fixes a problem

### ISSUE THREAD

**Issue by Moebius-Strip** [pseudonymous/better-better-booru#97]
Danbooru has removed some information from thumbnails that breaks this script and its own JavaScript so I'm waiting to see what is done before trying to resolve the problem.

**Comment by ForsakenRei** [comment]
Seems autopageing is dead. I didn't find any other problems.

**Comment by Moebius-Strip** [comment]
Oh trust me, there was more broken than you think. However it was all due to one problem so it wasn't too hard to mend.
